### ISSUE TITLE
Project incorrectly adds characters and newlines

### ISSUE THREAD

**Issue by ghost** [umairsyed613/Serilog.Sinks.WinForms#5]
Let's try to get some mistakes fixed. Your project has a long way to go just to become usable by anyone who wants to produce a desirable and professional application. Unfortunately, there are no other packages of this kind that I can find.

Since I am only interested in using the RichTextBoxLogControl, let's exclusively use the RichTextBoxLogControl for the examples and explanations.

Please try to use correct terminology and provide the correct code needed, so that a dummy can understand. When you make up imaginary terminology or slang such as "fetch" and provide no example of what you are talking about, it makes no sense.

RichTextBoxLogControl Issue #1
When using your provided example code, your project is adding an unneeded and undesirable extra 'space' character at the end of every line in the output. This is not acceptable and should be fixed. The root cause is discussed in Issue #2.
The example code you are providing is the following:

            Log.Logger = new LoggerConfiguration()
                        .WriteToSimpleTextBox(new MessageTemplateTextFormatter("{Message} {Exception}"))
                        .CreateLogger();

The following image illustrates your incorrect implementation, which causes the extra space before the blinking cursor.
![gui1](https://user-images.githubusercontent.com/66349788/109340480-4d8b5780-7826-11eb-91bd-be5d08080f1c.png)

RichTextBoxLogControl Issue #2
Now let's try to avoid issue #1 by using the format that is used correctly and professionally by the Console Sink, but incorrectly by your project.
When using the example format provided by the Console Sink we have the following code:

            Log.Logger = new LoggerConfiguration()
                        .WriteTo.Console(outputTemplate: "{Message:lj}{NewLine}{Exception}")
                        .WriteToSimpleTextBox(new MessageTemplateTextFormatter("{Message:lj}{NewLine}{Exception}"))
                        .CreateLogger();

The following image illustrates your incorrect implementation of an unneeded and undesirable extra new line at the end of every line in the output. This is not acceptable and should be fixed. You should not be adding anything that the user didn't ask to be added and doesn't want.
![gui2](https://user-images.githubusercontent.com/66349788/109340712-96dba700-7826-11eb-99d2-2a7bf9b3bed4.png)

As you can see in the following image, the console produces a desirable, professional and correct result:
![cli1](https://user-images.githubusercontent.com/66349788/109340732-9d6a1e80-7826-11eb-89a3-a1c065872d4c.png)

**Comment by ghost** [comment]
RichTextBoxLogControl Issue #3

When new text is added to the RichTextBoxLogControl, the text is not displayed once enough output is displayed to require a scroll bar.

In the 2 images above you can see how the console correctly scrolls as more output is added, but the RichTextBoxLogControl does not scroll as new output is added.

Something like RichTextBoxLogControl.ScrollToCaret() should be used to display the log in a more desirable and professional manner.

**Comment by Talsiter** [comment]
WOW, you are mighty condescending. Where can I download **your** **FREE** professional application at? I think that **YOU** need to change your tone. **YOU** should act more professional in your communication. IF **YOU** really want to help, can you not contribute to the software?

**YOU**, don't be a jerk, hiding anonymously behind your keyboard in your moms basement eating Cheeto's.   

I love the control. Any issues that I have had, have been quickly addressed and corrected. I was not rude or snarky because I value and appreciate the time someone volunteered to develop this control. They provided it to you for **FREE** so show a little application or shut up.

People like you, "**TommyS7000**", sicken me

**Comment by Talsiter** [comment]
Last thing "**TommyS7000**" please take some personal responsibility for YOUR code. The issues that you addressed should be fixed in YOUR code. I have no issues with it.

**Umair Syed**, you can go ahead and kick me off this forum, I deserve it. I cant stand a punk bully.

**Comment by umairsyed613** [comment]
@TommyS7000  the things you are saying can be fixed in your code. The controls are standard Microsoft control. You can configure anything in your code. And regarding the space thingy that can be fixed by providing the template when doing the configuration. And last thing is if you find room for improvement in this project you are very welcome to contribute and make a pull request with all the Professional changes that this project should have. :)

**Comment by umairsyed613** [comment]
Closing this with this release. https://github.com/umairsyed613/Serilog.Sinks.WinForms/releases/tag/2.2.6
check the release notes. hopefully, this solves your space at end issue since that part can be configured through your code. but I have changed the default template.
